config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user do
    mount Sidekiq::Web => '/admin/sidekiq'
    mount Flipper::UI.app(Flipper) => '/admin/flipper'
  end

  mount ActionCable.server => '/cable'
  mount SwaggerUiEngine::Engine, at: '/api_docs'

  devise_for :users, skip: %i[sessions registrations passwords confirmations]
  as :user do
    get '(:locale)/users/sign_in' => 'users/sessions#new', as: :new_user_session
    post '(:locale)/users/sign_in' => 'users/sessions#create', as: :user_session
    delete '(:locale)/users/sign_out' => 'users/sessions#destroy', as: :destroy_user_session
    get '(:locale)/users/sign_up' => 'users/registrations#new', as: :new_user_registration
    post '(:locale)/users/sign_up' => 'users/registrations#create', as: :user_registration
    get '(:locale)/users/passwords/new' => 'users/passwords#new', as: :new_user_password
    post '(:locale)/users/passwords/new' => 'users/passwords#create', as: :user_password
    put '(:locale)/users/passwords/new' => 'users/passwords#update'
    get '(:locale)/users/passwords/edit' => 'users/passwords#edit', as: :edit_user_password
    put '(:locale)/users/passwords/edit' => 'users/passwords#update'
    get '(:locale)/users/confirmation/new' => 'users/confirmations#new', as: :new_user_confirmation
    get '(:locale)/users/confirmation' => 'users/confirmations#show', as: :show_user_confirmation
    post '(:locale)/users/confirmation' => 'users/confirmations#create', as: :user_confirmation
  end

  scope '(:locale)', locale: /en|ar/ do
    root to: 'home#index'
    resource :home, only: :index

    devise_scope :user do
      get '/users/registrations/notification' => 'users/registrations#notification'
      get '/users/password/notification' => 'users/passwords#notification'
    end
  end

  namespace :admin do
    root to: 'dashboards#index'
    resources :dashboards

    resources :hotels
    resources :audits do
      member do
        post :initiate
        post :force_run
      end
    end

    resource :generator do
      # get :new_hotel
      post :create_hotel
      # get :new_reservation
      post :create_reservation
      # get :new_reservations
      post :create_reservations
    end

    resources :reservations
    resources :invoices
    resources :users

    resources :serviceworkers, only: :index
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :docs, only: :index

      scope '(:locale)', locale: /en|ar/ do
        resources :docs, only: :index
        resources :countries, only: %i[index show], param: :alpha3

        namespace :rooms do
          resources :amenities, only: %i[index create update destroy show]
          resources :room_types, only: %i[index create update destroy show]
          resources :rooms, only: %i[index create update destroy show]
          resources :available_rooms, only: %i[index]
        end

        namespace :hotels do
          resource :logo, except: %i[new edit]
          resource :offline_mode, only: %i[show update]
          resource :address, only: %i[show update]
          resource :check_time, only: %i[show update]
          resource :configuration, only: %i[show update]
        end

        scope module: :hotels do
          resource :hotel, only: %i[show update]
        end

        namespace :reservations do
          resources :dnr
          resources :adults, only: %i[create update show destroy]
          resources :invoices, module: :invoices, only: %i[show]
        end

        namespace :audits do
          resources :confirmations, only: [:index] do
            post :confirm, on: :member
          end
          resources :audits, only: [:show] do
            get :last, on: :collection
            get :last_completed, on: :collection
          end
        end

        resources :reservations, module: :reservations, except: %i[new edit] do
          member do
            patch :cancel
            patch :check_in
            patch :check_out
          end
        end

        resources :invoices, only: %i[show], module: :invoices do
          resources :payments, only: %i[index create update show destroy]
          resources :refunds, only: %i[create update show destroy]
          resources :discounts, only: %i[create update show destroy]
          resources :charges, only: %i[index create update show destroy]
        end

        scope module: :guests do
          resources :guests, only: [:index] do
            post :search, on: :collection
          end
        end

        resources :notifications, module: :notifications, only: %i[index show create] do
          post :preview, on: :collection
          patch :read, on: :member
        end

        resources :profiles, module: :profiles, only: [] do
          put :update, on: :collection
          get :show, on: :collection
        end

        namespace :reports do
          resources :reservations, only: %i[index]
        end

        namespace :rates do
          resources :rates, only: %i[index]
          resources :periods, only: %i[index show update create destroy] do
            get :standard, on: :collection
          end
        end
      end
    end
  end

  get 'serviceworker.js', to: 'serviceworkers#index'
  get '*path', to: 'home#index', constraints: ->(req) { !(%r{/^\/uploads\/.*/} =~ req.fullpath) }
end

app/models/audits.rb
# frozen_string_literal: true

module Audits
  def self.table_name_prefix
    'audits_'
  end
end

app/models/audits/audit.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: audits
#
#  id               :bigint(8)        not null, primary key
#  started_at       :datetime
#  status           :integer
#  time_frame_begin :datetime
#  time_frame_end   :datetime
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  hotel_id         :bigint(8)
#

module Audits
  class Audit < ApplicationRecord
    self.table_name = 'audits'
    enum status: { scheduled: 0, waiting_for_confirmation: 1, confirmed: 2, running: 3, completed: 4, failed: 5 }

    belongs_to :hotel, class_name: '::Hotels::Hotel'
    has_many :confirmations
    has_many :error_logs, class_name: '::Audits::ErrorLog'
    has_many :charges, class_name: '::Invoices::Charge'
    has_one :pdf_report, class_name: '::Attachment', as: :attachable

    after_initialize :set_defaults, if: :new_record?

    def hours_coverage
      return unless time_frame_end && time_frame_begin

      ((time_frame_end - time_frame_begin) / 1.hour).round(2)
    end

    def night
      "#{time_frame_begin.to_date} - #{time_frame_end.to_date}"
    end

    private

    def set_defaults
      self.status ||= :scheduled
    end
  end
end

app/models/audits/confirmation.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: audits_confirmations
#
#  id           :bigint(8)        not null, primary key
#  user_id      :bigint(8)
#  audit_id     :bigint(8)
#  confirmed_at :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

module Audits
  class Confirmation < ApplicationRecord
    belongs_to :user
    belongs_to :audit

    scope :pending, -> { where(confirmed_at: nil) }
  end
end

app/models/audits/error_log.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: audits_error_logs
#
#  id             :bigint(8)        not null, primary key
#  auditable_type :string
#  meta           :jsonb
#  step           :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  audit_id       :bigint(8)
#  auditable_id   :bigint(8)
#

module Audits
  class ErrorLog < ApplicationRecord
    enum step: { update_reservations_status: 0, create_stay_charges: 1, send_report: 2, schedule_next_audit: 3 }

    belongs_to :audit, class_name: '::Audits::Audit'
    belongs_to :auditable, polymorphic: true
  end
end

app/controllers/admin/audits_controller.rb
# frozen_string_literal: true

module Admin
  class AuditsController < Admin::BaseController
    before_action :fetch_audit, except: :index

    def index
      @q = ::Audits::Audit.order('audits.created_at DESC').ransack(params[:q])
      @audits = @q.result.page(params[:page]).per(10)
    end

    def show; end

    # runs audit without confirmations
    def force_run
      result = ::Services::Audits::Perform.call(audit: @audit)

      flash[:notice] = 'Audit has been successfully finished' if result&.success?
      flash[:alert] = 'Audit has been failed' unless result&.success?

      redirect_to admin_audit_path(@audit)
    end

    # runs audit with confrimations
    def initiate
      result = ::Services::Audits::Initiate.call(audit: @audit)

      flash[:notice] = 'Audit has been successfully finished' if result&.success?
      flash[:alert] = 'Audit has been failed' unless result&.success?

      redirect_to admin_audit_path(@audit)
    end

    def destroy
      @audit.destroy
      redirect_to action: :index
    end

    private

    def fetch_audit
      @audit = ::Audits::Audit.find(params[:id])
    end
  end
end

app/controllers/api/v1/audits/audits_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Audits
      class AuditsController < ApiController
        AuditSerializer = ::Serializers::Audits::CurrentAuditSerializer

        before_action :fetch_audit, only: %i[show]

        def show
          success(response: serialize(authorize(@audit), AuditSerializer))
        end

        def last
          success(response: serialize(audits.last, AuditSerializer))
        end

        def last_completed
          success(response: serialize(audits.completed.order(time_frame_begin: :desc).first, AuditSerializer))
        end

        private

        def audits
          policy_scope(::Audits::Audit)
        end

        def fetch_audit
          @audit = audits.find(params[:id])
        end
      end
    end
  end
end

app/controllers/api/v1/audits/confirmations_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Audits
      class ConfirmationsController < ApiController
        ConfirmationSerializer = ::Serializers::Audits::ConfirmationSerializer

        before_action :fetch_confirmation, only: [:confirm]

        def index
          success(response: serialize(policy_scope(::Audits::Confirmation).pending, ConfirmationSerializer))
        end

        def confirm
          authorize @confirmation
          success(response: serialize(
            ::Services::Audits::Confirm.call(confirmation: @confirmation).value,
            ConfirmationSerializer
          ))
        end

        private

        def fetch_confirmation
          @confirmation = ::Audits::Confirmation.find(params[:id])
        end
      end
    end
  end
end

app/views/admin/audits/_charges.html.slim
- attrs = Invoices::Charge.new.attributes.without("updated_at").keys
.card.shadow.mb-4
  = link_to "#charges", class: 'd-block card-header py-3 collapsed',
                       data: { toggle: 'collapse' },
                       role: 'button',
                       aria: { expanded: true, controls: 'charges'} do
    h6.m-0.font-weight-bold.text-primary
      ' Charges generated by this audit:
      = @audit.charges.count

  .collapse#charges
    .card-body
      table.table.table-bordered.small
        thead
          - attrs.each do |attr_name|
            th = attr_name.humanize
        tbody
          - @audit.charges.each do |error_log|
            tr
              - attrs.each do |attr_name|
                td = error_log.public_send(attr_name)

app/views/admin/audits/_error_logs.html.slim
- attrs = Audits::ErrorLog.new.attributes.without("updated_at").keys
.card.shadow.mb-4
  = link_to "#errors", class: 'd-block card-header py-3 collapsed',
                       data: { toggle: 'collapse' },
                       role: 'button',
                       aria: { expanded: true, controls: 'errors'} do
    h6.m-0.font-weight-bold.text-primary
      ' Errors Logs:
      = @audit.error_logs.count

  .collapse#errors
    .card-body
      table.table.table-bordered
        thead
          - attrs.each do |attr_name|
            th = attr_name.humanize
        tbody
          - @audit.error_logs.each do |error_log|
            tr
              - attrs.each do |attr_name|
                td = error_log.public_send(attr_name)

app/views/admin/audits/_item.html.slim
tr *{id: dom_id(audit)}
  td = audit.id
  td = link_to "Hotel ##{audit.hotel_id}", admin_hotel_path(audit.hotel_id)
  td = audit.status
  td = audit.started_at ? l(audit.started_at, format: :long) : '-'
  td = audit.time_frame_begin ? "#{l(audit.time_frame_begin, format: :long)} - #{l(audit.time_frame_end, format: :long)}" : '-'
  td
    = link_to 'Details', admin_audit_path(audit), class: 'btn btn-primary btn-sm'

app/views/admin/audits/_search.html.slim
.row
  .col-lg-12
    = search_form_for @q, url: admin_audits_path, builder: SimpleForm::FormBuilder, class: 'form-inline' do |f|
     .form-row
        .col
          = f.input :hotel_id_eq, label: 'Hotel ID', required: false, input_html: { class: 'form-control' }
        .col
          = f.input :status_eq, as: :select,
                                collection: ::Audits::Audit.statuses,
                                input_html: { class: 'form-control' },
                                label: 'Status',
                                required: false

        = f.submit 'Search', class: 'btn btn-primary mt-4'
br

app/views/admin/audits/index.html.slim
.row
  .col-lg-12
    h1.page-header Audits

hr.sidebar-divider

= render 'search'

hr.sidebar-divider

.row
  .col-lg-12
    table.table.table.table-bordered.is-breakable
      tr
        th = ::Audits::Audit.human_attribute_name(:id)
        th = ::Audits::Audit.human_attribute_name(:hotel_id)
        th = ::Audits::Audit.human_attribute_name(:status)
        th = ::Audits::Audit.human_attribute_name(:started_at)
        th Period
        / th = sort_link(@q, :status_eq, 'Status')
        th Actions
      = render collection: @audits, partial: 'item', as: :audit

.row
  .col-lg-12
    = paginate @audits

app/views/admin/audits/show.html.slim
.row
  .col-lg-4
    h1.page-header = "Audit ##{@audit.id}"
  .col-lg-8
    - unless @audit.running?
      = button_to 'Initaite', initiate_admin_audit_path(@audit), class: 'btn btn-primary btn-sm mr-1 float-right', method: :post
      = button_to 'Force run', force_run_admin_audit_path(@audit), class: 'btn btn-primary btn-sm mr-1 float-right', method: :post

.row
  .col-lg-12
    .card.shadow.mb-4
      = link_to "#base", class: 'd-block card-header py-3', data: { toggle: 'collapse' }, role: 'button', aria: { expanded: true, controls: 'base'} do

        h6.m-0.font-weight-bold.text-primary Base Info
      .collapse.show#base
        .card-body
          table.table.table-bordered
            tbody
              tr
                td ID
                td = @audit.id
              tr
                td Hotel
                td = link_to "Hotel ##{@audit.hotel_id}", admin_hotel_path(@audit.hotel)
              tr
                td Status
                td = @audit.status
              tr
                td Started At
                td = @audit.started_at ? l(@audit.started_at, format: :long) : '-'
              tr
                td Period
                td = @audit.time_frame_begin ? "#{l(@audit.time_frame_begin, format: :long)} - #{l(@audit.time_frame_end, format: :long)}" : '-'
              tr
                td Last PDF report
                td = @audit.pdf_report&.file ? (link_to 'Download PDF', @audit.pdf_report.file.url) : ' - '
              tr
                td Reservations IDs to be marked as no-show
                td = @audit.hotel.reservations.must_be_marked_as_no_show(@audit.time_frame_end.to_date).pluck(:id).sort.join(', ')
    = render 'error_logs'
    = render 'charges'