config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user do
    mount Sidekiq::Web => '/admin/sidekiq'
    mount Flipper::UI.app(Flipper) => '/admin/flipper'
  end

  mount ActionCable.server => '/cable'
  mount SwaggerUiEngine::Engine, at: '/api_docs'

  devise_for :users, skip: %i[sessions registrations passwords confirmations]
  as :user do
    get '(:locale)/users/sign_in' => 'users/sessions#new', as: :new_user_session
    post '(:locale)/users/sign_in' => 'users/sessions#create', as: :user_session
    delete '(:locale)/users/sign_out' => 'users/sessions#destroy', as: :destroy_user_session
    get '(:locale)/users/sign_up' => 'users/registrations#new', as: :new_user_registration
    post '(:locale)/users/sign_up' => 'users/registrations#create', as: :user_registration
    get '(:locale)/users/passwords/new' => 'users/passwords#new', as: :new_user_password
    post '(:locale)/users/passwords/new' => 'users/passwords#create', as: :user_password
    put '(:locale)/users/passwords/new' => 'users/passwords#update'
    get '(:locale)/users/passwords/edit' => 'users/passwords#edit', as: :edit_user_password
    put '(:locale)/users/passwords/edit' => 'users/passwords#update'
    get '(:locale)/users/confirmation/new' => 'users/confirmations#new', as: :new_user_confirmation
    get '(:locale)/users/confirmation' => 'users/confirmations#show', as: :show_user_confirmation
    post '(:locale)/users/confirmation' => 'users/confirmations#create', as: :user_confirmation
  end

  scope '(:locale)', locale: /en|ar/ do
    root to: 'home#index'
    resource :home, only: :index

    devise_scope :user do
      get '/users/registrations/notification' => 'users/registrations#notification'
      get '/users/password/notification' => 'users/passwords#notification'
    end
  end

  namespace :admin do
    root to: 'dashboards#index'
    resources :dashboards

    resources :hotels
    resources :audits do
      member do
        post :initiate
        post :force_run
      end
    end

    resource :generator do
      # get :new_hotel
      post :create_hotel
      # get :new_reservation
      post :create_reservation
      # get :new_reservations
      post :create_reservations
    end

    resources :reservations
    resources :invoices
    resources :users

    resources :serviceworkers, only: :index
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :docs, only: :index

      scope '(:locale)', locale: /en|ar/ do
        resources :docs, only: :index
        resources :countries, only: %i[index show], param: :alpha3

        namespace :rooms do
          resources :amenities, only: %i[index create update destroy show]
          resources :room_types, only: %i[index create update destroy show]
          resources :rooms, only: %i[index create update destroy show]
          resources :available_rooms, only: %i[index]
        end

        namespace :hotels do
          resource :logo, except: %i[new edit]
          resource :offline_mode, only: %i[show update]
          resource :address, only: %i[show update]
          resource :check_time, only: %i[show update]
          resource :configuration, only: %i[show update]
        end

        scope module: :hotels do
          resource :hotel, only: %i[show update]
        end

        namespace :reservations do
          resources :dnr
          resources :adults, only: %i[create update show destroy]
          resources :invoices, module: :invoices, only: %i[show]
        end

        namespace :audits do
          resources :confirmations, only: [:index] do
            post :confirm, on: :member
          end
          resources :audits, only: [:show] do
            get :last, on: :collection
            get :last_completed, on: :collection
          end
        end

        resources :reservations, module: :reservations, except: %i[new edit] do
          member do
            patch :cancel
            patch :check_in
            patch :check_out
          end
        end

        resources :invoices, only: %i[show], module: :invoices do
          resources :payments, only: %i[index create update show destroy]
          resources :refunds, only: %i[create update show destroy]
          resources :discounts, only: %i[create update show destroy]
          resources :charges, only: %i[index create update show destroy]
        end

        scope module: :guests do
          resources :guests, only: [:index] do
            post :search, on: :collection
          end
        end

        resources :notifications, module: :notifications, only: %i[index show create] do
          post :preview, on: :collection
          patch :read, on: :member
        end

        resources :profiles, module: :profiles, only: [] do
          put :update, on: :collection
          get :show, on: :collection
        end

        namespace :reports do
          resources :reservations, only: %i[index]
        end

        namespace :rates do
          resources :rates, only: %i[index]
          resources :periods, only: %i[index show update create destroy] do
            get :standard, on: :collection
          end
        end
      end
    end
  end

  get 'serviceworker.js', to: 'serviceworkers#index'
  get '*path', to: 'home#index', constraints: ->(req) { !(%r{/^\/uploads\/.*/} =~ req.fullpath) }
end

app/controllers/admin/generators_controller.rb
# frozen_string_literal: true

module Admin
  class GeneratorsController < Admin::BaseController
    before_action :init_data

    def create_reservation
      result = ::Services::Generators::DirectReservationGenerator.call(
        params: params.permit![:reservations_reservation].merge(hotel_id: current_hotel.id)
      )

      if result.success?
        flash[:notice] = 'A new reservation has been successfully created.'
        redirect_to admin_reservation_path(result.value)
      else
        flash[:alert] = result.value
        render :show
      end
    end

    def create_reservations
      result = ::Services::Generators::ReservationsGenerator.call(
        params: params.permit![:reservations].merge(hotel_id: current_hotel.id)
      )

      if result.success?
        flash[:notice] = 'A new reservation has been successfully created.'
        redirect_to admin_reservations_path
      else
        flash[:alert] = result.value
        render :show
      end
    end

    def create_hotel
      result = ::Services::Generators::HotelGenerator.call(params: params)

      if result.success?
        flash[:notice] = 'Audit has been successfully finished'
        redirect_to admin_hotel_path(result.value)
      else
        @user = User.new(email: params[:user][:email])
        flash[:alert] = result.value
        render :show
      end
    end

    private

    def init_data
      @reservation = ::Reservations::Reservation.new
      @user        = User.new
    end
  end
end

app/views/admin/generators/_new_hotel.html.slim
.row
  .col-lg-12
    .card.shadow.mb-4
      = link_to "#generateHotel", class: 'd-block card-header py-3', data: { toggle: 'collapse' }, role: 'button', aria: { expanded: true, controls: 'generateHotel'} do

        h6.m-0.font-weight-bold.text-primary Generate user with a hotel
      .collapse.show#generateHotel
        .card-body
          p.small.text-secondary
            i.fa.fa-exclamation-circle
            '
            span
              | Generates a new user and a hotel with selected room types count. User password will be: Zaire123

          = simple_form_for @user, url: create_hotel_admin_generator_path, method: :post, class: 'form-inline' do |f|
            .form-row
              .col
                = f.input :email, input_html: { class: 'form-control'}, required: false
              = simple_fields_for :room_types do |room_types_form|
                .col
                  = room_types_form.input :room_types_count, input_html: { value: 1, class: 'form-control'}, required: false
                .col
                  = room_types_form.input :rooms_count, input_html: { value: 1, class: 'form-control'}, required: false
            = f.button :submit, 'Generate Hotel', class: 'btn btn-primary mt-4'

app/views/admin/generators/_new_reservation.html.slim
.row
  .col-lg-12
    .card.shadow.mb-4
      = link_to "#generateReservation", class: 'd-block card-header py-3', data: { toggle: 'collapse' }, role: 'button', aria: { expanded: true, controls: 'generateReservation'} do

        h6.m-0.font-weight-bold.text-primary Generate a reservation for the Current hotel
      .collapse.show#generateReservation
        .card-body
          p.small.text-secondary
            i.fa.fa-exclamation-circle
            '
            span
              | Generates a new reservation. If choose confirmed: generates with a payment. If choose checked_in: generates with 1 adult.
              | Please be careful, it does not check for overlaps for now.

          - rooms = current_hotel.rooms.includes(:room_type).pluck("CONCAT_WS(' - ', room_types.name, rooms.number)", 'rooms.id')
          = simple_form_for @reservation, url: create_reservation_admin_generator_path, method: :post, class: 'form' do |f|
            .form-row
              / = f.input :hotel_id, as: :hidden, value: current_hotel.id
              .col
                = f.input :room_id, collection: rooms, input_html: { class: 'form-control'}, required: false, include_blank: false
              .col
                = f.input :check_in_date, as: :date, html5: true, input_html: { value: Date.current.strftime, class: 'form-control'}, required: false
              .col
                = f.input :check_out_date, as: :date, html5: true, input_html: { value: Date.tomorrow.strftime, class: 'form-control'}, required: false
              .col
                = f.input :status, collection: ::Reservations::Reservation.statuses.keys, input_html: { class: 'form-control'}, required: false, include_blank: false
              .col
                = f.input :rate, collection: ::Reservations::Reservation.rates.keys, input_html: { class: 'form-control'}, required: false, include_blank: false
              .col
                = f.input :payment_kind, collection: ::Reservations::Reservation.payment_kinds.keys, input_html: { class: 'form-control'}, required: false, include_blank: false
            = f.button :submit, 'Generate Reservation', class: 'btn btn-primary mt-4'

app/views/admin/generators/_new_reservations.html.slim
.row
  .col-lg-12
    .card.shadow.mb-4
      = link_to "#generateReservations", class: 'd-block card-header py-3', data: { toggle: 'collapse' }, role: 'button', aria: { expanded: true, controls: 'generateReservation'} do

        h6.m-0.font-weight-bold.text-primary Generate a reservations for the Current hotel
      .collapse.show#generateReservation
        .card-body
          p.small.text-secondary
            i.fa.fa-exclamation-circle
            '
            span
              | Generates a new reservations. If choose confirmed: generates with a payment. If choose checked_in: generates with 1 adult.

          = simple_form_for :reservations, url: create_reservations_admin_generator_path, method: :post, class: 'form' do |f|
            .form-row
              .col
                = f.input :count, input_html: { value: 1, class: 'form-control'}, required: false
              .col
                = f.input :check_in_date, as: :date, html5: true, input_html: { value: Date.current.strftime, class: 'form-control'}, required: false
              .col
                = f.input :check_out_date, as: :date, html5: true, input_html: { value: Date.tomorrow.strftime, class: 'form-control'}, required: false
              .col
                = f.input :status, collection: ::Reservations::Reservation.statuses.keys, input_html: { class: 'form-control'}, required: false, include_blank: false
              .col
                = f.input :rate, collection: ::Reservations::Reservation.rates.keys, input_html: { class: 'form-control'}, required: false, include_blank: false
              .col
                = f.input :payment_kind, collection: ::Reservations::Reservation.payment_kinds.keys, input_html: { class: 'form-control'}, required: false, include_blank: false
            = f.button :submit, 'Generate Reservations', class: 'btn btn-primary mt-4'

app/views/admin/generators/show.html.slim
.row
  .col-lg-12
    h1.page-header Generators

= render 'new_hotel'
= render 'new_reservation'
= render 'new_reservations'