config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user do
    mount Sidekiq::Web => '/admin/sidekiq'
    mount Flipper::UI.app(Flipper) => '/admin/flipper'
  end

  mount ActionCable.server => '/cable'
  mount SwaggerUiEngine::Engine, at: '/api_docs'

  devise_for :users, skip: %i[sessions registrations passwords confirmations]
  as :user do
    get '(:locale)/users/sign_in' => 'users/sessions#new', as: :new_user_session
    post '(:locale)/users/sign_in' => 'users/sessions#create', as: :user_session
    delete '(:locale)/users/sign_out' => 'users/sessions#destroy', as: :destroy_user_session
    get '(:locale)/users/sign_up' => 'users/registrations#new', as: :new_user_registration
    post '(:locale)/users/sign_up' => 'users/registrations#create', as: :user_registration
    get '(:locale)/users/passwords/new' => 'users/passwords#new', as: :new_user_password
    post '(:locale)/users/passwords/new' => 'users/passwords#create', as: :user_password
    put '(:locale)/users/passwords/new' => 'users/passwords#update'
    get '(:locale)/users/passwords/edit' => 'users/passwords#edit', as: :edit_user_password
    put '(:locale)/users/passwords/edit' => 'users/passwords#update'
    get '(:locale)/users/confirmation/new' => 'users/confirmations#new', as: :new_user_confirmation
    get '(:locale)/users/confirmation' => 'users/confirmations#show', as: :show_user_confirmation
    post '(:locale)/users/confirmation' => 'users/confirmations#create', as: :user_confirmation
  end

  scope '(:locale)', locale: /en|ar/ do
    root to: 'home#index'
    resource :home, only: :index

    devise_scope :user do
      get '/users/registrations/notification' => 'users/registrations#notification'
      get '/users/password/notification' => 'users/passwords#notification'
    end
  end

  namespace :admin do
    root to: 'dashboards#index'
    resources :dashboards

    resources :hotels
    resources :audits do
      member do
        post :initiate
        post :force_run
      end
    end

    resource :generator do
      # get :new_hotel
      post :create_hotel
      # get :new_reservation
      post :create_reservation
      # get :new_reservations
      post :create_reservations
    end

    resources :reservations
    resources :invoices
    resources :users

    resources :serviceworkers, only: :index
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :docs, only: :index

      scope '(:locale)', locale: /en|ar/ do
        resources :docs, only: :index
        resources :countries, only: %i[index show], param: :alpha3

        namespace :rooms do
          resources :amenities, only: %i[index create update destroy show]
          resources :room_types, only: %i[index create update destroy show]
          resources :rooms, only: %i[index create update destroy show]
          resources :available_rooms, only: %i[index]
        end

        namespace :hotels do
          resource :logo, except: %i[new edit]
          resource :offline_mode, only: %i[show update]
          resource :address, only: %i[show update]
          resource :check_time, only: %i[show update]
          resource :configuration, only: %i[show update]
        end

        scope module: :hotels do
          resource :hotel, only: %i[show update]
        end

        namespace :reservations do
          resources :dnr
          resources :adults, only: %i[create update show destroy]
          resources :invoices, module: :invoices, only: %i[show]
        end

        namespace :audits do
          resources :confirmations, only: [:index] do
            post :confirm, on: :member
          end
          resources :audits, only: [:show] do
            get :last, on: :collection
            get :last_completed, on: :collection
          end
        end

        resources :reservations, module: :reservations, except: %i[new edit] do
          member do
            patch :cancel
            patch :check_in
            patch :check_out
          end
        end

        resources :invoices, only: %i[show], module: :invoices do
          resources :payments, only: %i[index create update show destroy]
          resources :refunds, only: %i[create update show destroy]
          resources :discounts, only: %i[create update show destroy]
          resources :charges, only: %i[index create update show destroy]
        end

        scope module: :guests do
          resources :guests, only: [:index] do
            post :search, on: :collection
          end
        end

        resources :notifications, module: :notifications, only: %i[index show create] do
          post :preview, on: :collection
          patch :read, on: :member
        end

        resources :profiles, module: :profiles, only: [] do
          put :update, on: :collection
          get :show, on: :collection
        end

        namespace :reports do
          resources :reservations, only: %i[index]
        end

        namespace :rates do
          resources :rates, only: %i[index]
          resources :periods, only: %i[index show update create destroy] do
            get :standard, on: :collection
          end
        end
      end
    end
  end

  get 'serviceworker.js', to: 'serviceworkers#index'
  get '*path', to: 'home#index', constraints: ->(req) { !(%r{/^\/uploads\/.*/} =~ req.fullpath) }
end

app/models/invoices.rb
# frozen_string_literal: true

module Invoices
  def self.table_name_prefix
    'invoices_'
  end
end

app/models/invoices/balance.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: invoices_balances
#
#  id         :bigint(8)        not null, primary key
#  amount     :decimal(10, 2)   default(0.0)
#  deleted_at :datetime
#  department :integer
#  owner_type :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  owner_id   :bigint(8)
#

module Invoices
  class Balance < ApplicationRecord
    acts_as_paranoid
    enum department: { default: 0 }

    belongs_to :owner, polymorphic: true

    after_initialize :set_defaults, if: :new_record?

    validates :department, presence: true

    def self.for(owner, department = :default)
      find_or_create_by(owner: owner, department: department)
    end

    private

    def set_defaults
      self.amount ||= 0
      self.department ||= :default
    end
  end
end

app/models/invoices/discount.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: invoices_discounts
#
#  id           :bigint(8)        not null, primary key
#  creation_way :integer
#  deleted_at   :datetime
#  description  :text
#  kind         :integer          default("amount")
#  value        :decimal(10, 2)   default(0.0)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  invoice_id   :bigint(8)
#  user_id      :bigint(8)
#

module Invoices
  class Discount < ApplicationRecord
    has_paper_trail only: %i[value description kind user_id], on: %i[update]
    acts_as_paranoid

    enum kind: { amount: 0, percent: 1 }
    enum creation_way: { manual: 0, automated: 1 }

    belongs_to :user
    belongs_to :invoice, class_name: '::Invoices::Invoice'
  end
end

app/controllers/admin/invoices_controller.rb
# frozen_string_literal: true

module Admin
  class InvoicesController < Admin::BaseController
    before_action :fetch_invoice, except: :index

    def index
      @q = ::Invoices::Invoice.order('invoices.created_at DESC').ransack(params[:q])
      @invoices = @q.result.page(params[:page]).per(10)
    end

    def show; end

    def destroy
      @invoice.destroy
      redirect_to action: :index
    end

    private

    def fetch_invoice
      @invoice = ::Invoices::Invoice.find(params[:id])
    end
  end
end

app/controllers/api/v1/invoices/base_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Invoices
      class BaseController < ApiController
        before_action :fetch_invoice

        private

        def fetch_invoice
          @invoice = policy_scope(::Invoices::Invoice).find(params[:invoice_id])
        end
      end
    end
  end
end

app/controllers/api/v1/invoices/charges_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Invoices
      class ChargesController < BaseController
        before_action :set_charge, only: %i[update destroy show]
        before_action -> { authorize @invoice }, except: %i[index]

        def index
          success(response: serialize(@invoice.charges, ::Serializers::Invoices::ChargeSerializer))
        end

        def create
          charge = @invoice.charges.create!(validated_params)
          ::Services::Invoices::RecalculateInvoice.call(statement: charge)
          success(status: 201, response: ::Serializers::Invoices::ChargeSerializer.new(charge))
        end

        def update
          @charge.update!(validated_params)
          ::Services::Invoices::RecalculateInvoice.call(statement: @charge)
          success(response: ::Serializers::Invoices::ChargeSerializer.new(@charge))
        end

        def destroy
          @charge.destroy!
          ::Services::Invoices::RecalculateInvoice.call(statement: @charge)
          success(response: { id: @charge.id })
        end

        def show
          success(response: serialize(@charge, ::Serializers::Invoices::ChargeSerializer))
        end

        private

        def set_charge
          @charge = @invoice.charges.find(params[:id])
        end

        def validated_params
          @validated_params ||= charge_params
        end

        def charge_params
          keys = %i[id amount description user_id kind creation_way]
          params.require(:charge).permit(*keys).merge!(user_id: current_user.id, kind: :sellable_items)
        end
      end
    end
  end
end

app/controllers/api/v1/invoices/discounts_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Invoices
      class DiscountsController < BaseController
        before_action :set_discount, only: %i[update destroy show]

        def create
          discount = @invoice.discounts.new(validated_params)
          authorize discount

          @invoice.transaction do
            discount.save!
            result = ::Services::Invoices::RecalculateInvoice.call(statement: discount)

            if result.success?
              ::Services::Reservations::Statuses::DetermineStatus.call(reservation: @invoice.reservation)
              success(status: 201, response: ::Serializers::Invoices::DiscountSerializer.new(discount))
            else
              error(message: result.value)
              raise ActiveRecord::Rollback
            end
          end
        end

        def update
          authorize @discount

          @invoice.transaction do
            @discount.update!(validated_params)
            result = ::Services::Invoices::RecalculateInvoice.call(statement: @discount)

            if result.success?
              ::Services::Reservations::Statuses::DetermineStatus.call(reservation: @invoice.reservation)
              success(response: ::Serializers::Invoices::DiscountSerializer.new(@discount))
            else
              error(message: result.value)
              raise ActiveRecord::Rollback
            end
          end
        end

        def destroy
          authorize @discount

          @invoice.transaction do
            @discount.destroy!
            result = ::Services::Invoices::RecalculateInvoice.call(statement: @discount)

            if result.success?
              ::Services::Reservations::Statuses::DetermineStatus.call(reservation: @invoice.reservation)
              success(response: ::Serializers::Invoices::DiscountSerializer.new(@discount))
            else
              error(message: result.value)
              raise ActiveRecord::Rollback
            end
          end
        end

        def show
          authorize @discount
          success(response: serialize(@discount, ::Serializers::Invoices::DiscountSerializer))
        end

        private

        def set_discount
          @discount = @invoice.discounts.find(params[:id])
        end

        def validated_params
          @validated_params ||=
            ::Validators::Invoices::DiscountValidator.new(discount_params, @discount).to_hash
        end

        def discount_params
          default_values = { user_id: current_user.id, creation_way: 'manual' }
          keys = %i[id value kind description creation_way]
          params.require(:discount).permit(*keys).merge!(default_values)
        end
      end
    end
  end
end

app/controllers/api/v1/invoices/invoices_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Invoices
      class InvoicesController < ApiController
        def show
          @invoice = ::Invoices::Invoice.find(params[:id])
          authorize @invoice

          success(response: serialize(@invoice, ::Serializers::Invoices::InvoiceSerializer))
        end
      end
    end
  end
end

app/controllers/api/v1/invoices/payments_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Invoices
      class PaymentsController < BaseController
        before_action :set_payment, only: %i[update destroy show]

        def index
          authorize ::Invoices::Payment
          success(response: serialize(policy_scope(@invoice.payments), ::Serializers::Invoices::PaymentSerializer))
        end

        def create
          payment = @invoice.payments.new(validated_params)
          authorize payment
          @invoice.transaction do
            payment.save!
            ::Services::Invoices::RecalculateInvoice.call(statement: payment)
            ::Services::Reservations::Statuses::DetermineStatus.call(reservation: reservation)
          end
          success(status: 201, response: ::Serializers::Invoices::PaymentSerializer.new(payment))
        end

        def update
          authorize @payment
          @payment.update!(validated_params)
          ::Services::Invoices::RecalculateInvoice.call(statement: @payment)
          ::Services::Reservations::Statuses::DetermineStatus.call(reservation: reservation)
          success(response: ::Serializers::Invoices::PaymentSerializer.new(@payment))
        end

        def destroy
          authorize @payment
          @payment.destroy!
          ::Services::Invoices::RecalculateInvoice.call(statement: @payment)
          ::Services::Reservations::Statuses::DetermineStatus.call(reservation: reservation)
          success(response: ::Serializers::Invoices::PaymentSerializer.new(@payment))
        end

        def show
          authorize @payment
          success(response: serialize(@payment, ::Serializers::Invoices::PaymentSerializer))
        end

        private

        def reservation
          @reservation ||= @invoice.reservation
        end

        def set_payment
          @payment = @invoice.payments.find(params[:id])
        end

        def validated_params
          @validated_params ||= ::Validators::Invoices::PaymentValidator.new(payment_params, @payment).to_hash
        end

        def payment_params
          default_values = { user_id: current_user.id, creation_way: 'manual' }
          keys = %i[id amount user_id creation_way payment_method]
          params.require(:payment).permit(*keys).merge!(default_values)
        end
      end
    end
  end
end

app/controllers/api/v1/invoices/refunds_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Invoices
      class RefundsController < BaseController
        before_action :set_refund, only: %i[update destroy show]

        def create
          refund = @invoice.refunds.new(validated_params)
          authorize refund
          refund.save!
          ::Services::Invoices::RecalculateInvoice.call(statement: refund)
          ::Services::Reservations::Statuses::DetermineStatus.call(reservation: @invoice.reservation)
          success(status: 201, response: ::Serializers::Invoices::RefundSerializer.new(refund))
        end

        def update
          authorize @refund
          @refund.update!(validated_params)
          ::Services::Invoices::RecalculateInvoice.call(statement: @refund)
          ::Services::Reservations::Statuses::DetermineStatus.call(reservation: @invoice.reservation)
          success(response: ::Serializers::Invoices::RefundSerializer.new(@refund))
        end

        def destroy
          authorize @refund
          @refund.destroy!
          ::Services::Invoices::RecalculateInvoice.call(statement: @refund)
          ::Services::Reservations::Statuses::DetermineStatus.call(reservation: @invoice.reservation)
          success(response: ::Serializers::Invoices::RefundSerializer.new(@refund))
        end

        def show
          authorize @refund
          success(response: serialize(@refund, ::Serializers::Invoices::RefundSerializer))
        end

        private

        def set_refund
          @refund = @invoice.refunds.find(params[:id])
        end

        def validated_params
          @validated_params ||=
            ::Validators::Invoices::RefundValidator.new(refund_params, @refund).to_hash
        end

        def refund_params
          default_values = { user_id: current_user.id, creation_way: 'manual' }
          keys = %i[id amount payment_id description creation_way]
          params.require(:refund).permit(*keys).merge!(default_values)
        end
      end
    end
  end
end

app/views/admin/invoices/_charges.html.slim
- attrs = Invoices::Charge.new.attributes.without("deleted_at").keys
.card.mb-4
  .card-header.py-3
    h6.m-0.font-weight-bold.text-primary
      | Charges: #{@invoice.charges.count}
  .card-body
    table.table.table-bordered.small
      thead
        - attrs.each do |attr_name|
          th = attr_name.humanize
      tbody
        - @invoice.charges.each do |error_log|
          tr
            - attrs.each do |attr_name|
              td = error_log.public_send(attr_name)

app/views/admin/invoices/_discounts.html.slim
- attrs = Invoices::Discount.new.attributes.without("deleted_at").keys
.card.mb-4
  .card-header.py-3
    h6.m-0.font-weight-bold.text-primary
      | Discounts: #{@invoice.discounts.count}
  .card-body
    table.table.table-bordered.small
      thead
        - attrs.each do |attr_name|
          th = attr_name.humanize
      tbody
        - @invoice.discounts.each do |error_log|
          tr
            - attrs.each do |attr_name|
              td = error_log.public_send(attr_name)

app/views/admin/invoices/_item.html.slim
tr.small *{id: dom_id(invoice)}
  td = invoice.id
  td = invoice.to_id ? (link_to "Reservation ##{invoice.to_id}", admin_reservation_path(invoice.to_id)) : ' - '
  td = invoice.vat_tax
  td = invoice.municipal_tax
  td = invoice.charges_total
  td = invoice.refunds_total
  td = invoice.payments_total
  td = invoice.discounts_total
  td = invoice.charges_with_taxes_total
  td = invoice.booking_total
  td = invoice.amount
  td
    = link_to 'Details', admin_invoice_path(invoice), class: 'btn btn-primary btn-sm'

app/views/admin/invoices/_payments.html.slim
- attrs = Invoices::Payment.new.attributes.without("deleted_at").keys
.card.mb-4
  .card-header.py-3
    h6.m-0.font-weight-bold.text-primary
      | Payments: #{@invoice.payments.count}
  .card-body
    table.table.table-bordered.small
      thead
        - attrs.each do |attr_name|
          th = attr_name.humanize
      tbody
        - @invoice.payments.each do |error_log|
          tr
            - attrs.each do |attr_name|
              td = error_log.public_send(attr_name)

app/views/admin/invoices/_refunds.html.slim
- attrs = Invoices::Refund.new.attributes.without("deleted_at").keys
.card.mb-4
  .card-header.py-3
    h6.m-0.font-weight-bold.text-primary
      | Refunds: #{@invoice.refunds.count}
  .card-body
    table.table.table-bordered.small
      thead
        - attrs.each do |attr_name|
          th = attr_name.humanize
      tbody
        - @invoice.refunds.each do |error_log|
          tr
            - attrs.each do |attr_name|
              td = error_log.public_send(attr_name)

app/views/admin/invoices/_search.html.slim
.row
  .col-lg-12
    = search_form_for @q, url: admin_invoices_path, builder: SimpleForm::FormBuilder, class: 'form-inline' do |f|
     .form-row
        .col
          = f.input :reservation_id_eq, label: 'Reservation ID', required: false, input_html: { class: 'form-control' }

        = f.submit 'Search', class: 'btn btn-primary mt-4'
br

app/views/admin/invoices/index.html.slim
.row
  .col-lg-12
    h1.page-header = "Invoices"

hr.sidebar-divider

= render 'search'

hr.sidebar-divider

.row
  .col-lg-12
    table.table.table.table-bordered.is-breakable
      tr
        th ID
        th Reservation ID
        th Vat tax
        th Municipal tax
        th Charges total
        th Refunds total
        th Payments total
        th Discounts total
        th Charges with taxes total
        th Booking total
        th Amount
        th Actions
      = render collection: @invoices, partial: 'item', as: :invoice

.row
  .col-lg-12
    = paginate @invoices

app/views/admin/invoices/show.html.slim
.row
  .col-lg-5
    h1.page-header = "Invoice for Reservation ##{@invoice.to_id}"

  .col-lg-7
    = link_to 'Reservation', admin_reservation_path(@invoice.to_id), class: 'btn btn-primary btn-sm mr-1 float-right'

.row
  .col-lg-12
    .card.shadow.mb-4
      = link_to "#base", class: 'd-block card-header py-3 collapsed',
                           data: { toggle: 'collapse' },
                           role: 'button',
                           aria: { expanded: true, controls: 'base'} do
        h6.m-0.font-weight-bold.text-primary Base info
      .collapse#base
        .card-body
          - attrs = Invoices::Invoice.new.attributes.without("deleted_at").keys
          table.table.table-bordered.small
            tbody
              - attrs.each do |attr_name|
                tr
                  td = attr_name.humanize
                  td = @invoice.public_send(attr_name)

    = render 'charges'
    = render 'discounts'
    = render 'payments'
    = render 'refunds'